#!/usr/bin/env node
// Builds a fully static copy of the site into out/ for static or shared
// hosting (Apache/cPanel, Nginx, S3, GitHub Pages, ...).
//
//   node scripts/build-spa.mjs
//
// Server-only parts (app/api route handlers and the middleware) are moved
// aside for the duration of the build and restored afterwards, even if the
// build fails. Features backed by those routes (website screenshots, tweet
// import, server-side export) are unavailable in the static copy.

import { execSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const outDir = path.join(root, "out");
const stashDir = path.join(root, ".spa-stash");
const defaultLocale = "en";

// Paths (relative to the repo root) that need a Node server.
const serverOnly = ["app/api", "middleware.ts"];

function stash() {
  mkdirSync(stashDir, { recursive: true });
  for (const rel of serverOnly) {
    const from = path.join(root, rel);
    if (existsSync(from)) renameSync(from, path.join(stashDir, rel.replaceAll("/", "__")));
  }
}

function restore() {
  for (const rel of serverOnly) {
    const from = path.join(stashDir, rel.replaceAll("/", "__"));
    if (existsSync(from)) renameSync(from, path.join(root, rel));
  }
  rmSync(stashDir, { recursive: true, force: true });
}

// Pages for the default locale are linked without a prefix ("/editor", not
// "/en/editor"). Without middleware to rewrite them, copy them to the root.
function hoistDefaultLocale() {
  const localeDir = path.join(outDir, defaultLocale);
  if (!existsSync(localeDir)) return;
  for (const entry of readdirSync(localeDir)) {
    cpSync(path.join(localeDir, entry), path.join(outDir, entry), {
      recursive: true,
      force: true,
    });
  }
  // "/" is rendered as out/en.html + out/en.txt (or out/en/index.html).
  for (const ext of ["html", "txt"]) {
    const file = path.join(outDir, `${defaultLocale}.${ext}`);
    if (existsSync(file)) cpSync(file, path.join(outDir, `index.${ext}`));
  }
}

// Apache equivalents of the headers and redirects in next.config.ts.
function writeHtaccess() {
  const isolated = "editor|remove-background|(es|fr|de|ja|pt|ko|zh)/(editor|remove-background)";
  const htaccess = `# Generated by scripts/build-spa.mjs
Options -MultiViews
DirectorySlash On
DirectoryIndex index.html
ErrorDocument 404 /404.html

<IfModule mod_mime.c>
  AddType application/wasm .wasm
  AddType text/plain .txt
  AddType application/javascript .mjs
</IfModule>

<IfModule mod_rewrite.c>
  RewriteEngine On

  # Permanent redirects (mirrors redirects() in next.config.ts)
  RewriteRule ^features/background-remover/?$ /remove-background/ [R=301,L]
  RewriteRule ^home/?$ /editor/ [R=301,L]
  RewriteRule ^free-screenshot-editor-online/?$ /free-screenshot-editor/ [R=301,L]
  RewriteRule ^free-screenshot-studio(/.*)?$ /free-screenshot-editor/ [R=301,L]
  RewriteRule ^blog/(.*)$ /guides/$1 [R=301,L]

  # Mark cross-origin-isolated pages so the header rules below can match them
  RewriteRule ^(${isolated})(/.*)?$ - [E=COI:1]
</IfModule>

<IfModule mod_headers.c>
  Header always set X-Content-Type-Options "nosniff"
  Header always set Referrer-Policy "strict-origin-when-cross-origin"
  Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"

  # SharedArrayBuffer for FFmpeg / ONNX WASM (multi-threaded)
  Header always set Cross-Origin-Opener-Policy "same-origin" env=COI
  Header always set Cross-Origin-Embedder-Policy "credentialless" env=COI
  Header always set Cross-Origin-Opener-Policy "same-origin" env=REDIRECT_COI
  Header always set Cross-Origin-Embedder-Policy "credentialless" env=REDIRECT_COI

  <If "%{REQUEST_URI} =~ m#^/_next/static/#">
    Header always set Cross-Origin-Embedder-Policy "credentialless"
    Header always set Cache-Control "public, max-age=31536000, immutable"
  </If>
</IfModule>
`;
  writeFileSync(path.join(outDir, ".htaccess"), htaccess);
}

// Netlify / Cloudflare Pages style header file, for hosts that read it.
function writeHeadersFile() {
  const coi = [
    "  Cross-Origin-Opener-Policy: same-origin",
    "  Cross-Origin-Embedder-Policy: credentialless",
  ].join("\n");
  const isolatedPaths = ["/editor/*", "/remove-background/*"];
  for (const locale of ["es", "fr", "de", "ja", "pt", "ko", "zh"]) {
    isolatedPaths.push(`/${locale}/editor/*`, `/${locale}/remove-background/*`);
  }
  const body = [
    "/*",
    "  X-Content-Type-Options: nosniff",
    "  Referrer-Policy: strict-origin-when-cross-origin",
    "",
    ...isolatedPaths.flatMap((p) => [p, coi, ""]),
    "/_next/static/*",
    "  Cross-Origin-Embedder-Policy: credentialless",
    "  Cache-Control: public, max-age=31536000, immutable",
    "",
  ].join("\n");
  writeFileSync(path.join(outDir, "_headers"), body);
}

stash();
let failed = false;
try {
  rmSync(outDir, { recursive: true, force: true });
  execSync("npx prisma generate && npx next build --webpack", {
    cwd: root,
    stdio: "inherit",
    env: {
      // Prisma only backs the API routes, which are not part of this build,
      // but `prisma generate` still wants a connection string to be set.
      DATABASE_URL: "postgresql://static:static@localhost:5432/static",
      ...process.env,
      STATIC_EXPORT: "1",
    },
  });
} catch {
  failed = true;
} finally {
  restore();
}
if (failed) process.exit(1);

hoistDefaultLocale();
writeHtaccess();
writeHeadersFile();
writeFileSync(path.join(outDir, ".nojekyll"), "");
console.log(`\nStatic site written to ${path.relative(root, outDir)}/`);
